INDEX_HTML = """<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>章悟式∞競輪OS PR31</title>
<style>:root{font-family:system-ui,-apple-system,"Noto Sans JP",sans-serif;background:#f3f5f7;color:#17212b}*{box-sizing:border-box}body{margin:0}.wrap{max-width:760px;margin:auto;padding:12px}.card{background:#fff;border-radius:18px;padding:16px;margin:12px 0;box-shadow:0 8px 24px #17212b12}h1{font-size:24px}.notice{background:#edf8f2;border-radius:12px;padding:12px;font-weight:800;line-height:1.55}.file{display:block;margin:12px 0;padding:14px 16px;border:2px solid #087d49;border-radius:14px;font-weight:900;cursor:pointer}.file input{display:none}.fileTitle{display:block;font-size:16px}.fileName{display:block;margin-top:5px;font-size:13px;font-weight:600;color:#56636d;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pin{width:100%;height:48px;border:1px solid #bbc4cb;border-radius:10px;padding:8px;font-size:17px}.submit{width:100%;height:60px;border:0;border-radius:14px;background:#087d49;color:#fff;font-size:18px;font-weight:900;margin-top:14px}.submit:disabled{opacity:.65}.pick{display:grid;grid-template-columns:62px 1fr 90px;gap:8px;padding:10px 0;border-bottom:1px solid #e5e9ec}.pair{font-size:20px;font-weight:900}.sub{font-size:13px;color:#56636d}.right{text-align:right;font-weight:800}.bad{color:#b11919;font-weight:800;white-space:pre-wrap}.tag{display:inline-block;background:#fff1cc;border-radius:999px;padding:4px 8px;margin:3px;font-size:12px;font-weight:800}</style></head>
<body><main class="wrap"><h1>章悟式∞競輪OS PR31</h1><section class="card"><div class="notice">PR #31 Frozen<br>2日目以降：前日の負けて強し／展開不利を確認<br>初日：前日補正なし</div><form id="form"><label class="file"><span class="fileTitle">① 基本情報PDF</span><span class="fileName" id="basicName">競走得点・逃・捲・差・マ・B</span><input id="basicPdf" name="basic_pdf" type="file" accept="application/pdf,.pdf" required></label><label class="file"><span class="fileTitle">② H/S・着度数PDF</span><span class="fileName" id="hsName">1着・2着・3着・着外・H・S</span><input id="hsPdf" name="hs_pdf" type="file" accept="application/pdf,.pdf" required></label><label class="file"><span class="fileTitle">③ 2車単オッズPDF</span><span class="fileName" id="oddsName">並び・2車単オッズ</span><input id="oddsPdf" name="odds_pdf" type="file" accept="application/pdf,.pdf" required></label><p>専用PIN</p><input class="pin" type="password" name="pin"><button class="submit" id="submit">PR31で計算</button></form><p id="status"></p><p id="error" class="bad"></p></section><section id="result" hidden></section></main>
<script>
const form=document.querySelector('#form'),basicPdf=document.querySelector('#basicPdf'),hsPdf=document.querySelector('#hsPdf'),oddsPdf=document.querySelector('#oddsPdf'),basicName=document.querySelector('#basicName'),hsName=document.querySelector('#hsName'),oddsName=document.querySelector('#oddsName'),statusEl=document.querySelector('#status'),errorEl=document.querySelector('#error'),result=document.querySelector('#result'),submit=document.querySelector('#submit');
function bindFile(input,nameEl,fallback){input.addEventListener('change',()=>{nameEl.textContent=input.files[0]?.name||fallback;errorEl.textContent='';});}
bindFile(basicPdf,basicName,'競走得点・逃・捲・差・マ・B');bindFile(hsPdf,hsName,'1着・2着・3着・着外・H・S');bindFile(oddsPdf,oddsName,'並び・2車単オッズ');
const pct=v=>(Number(v||0)*100).toFixed(2)+'%';
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function render(data){const picks=(data.selections||[]).map(x=>`<div class="pick"><div class="pair">${x.first_car}-${x.second_car}</div><div class="sub">確率 ${pct(x.calibrated_probability)}<br>購入用率 ${pct(x.purchase_probability)}<br>オッズ ${Number(x.exacta_odds).toFixed(1)}</div><div class="right">EV ${Number(x.ev).toFixed(2)}</div></div>`).join('')||'<b>見送り</b>';const riders=(data.riders||[]).map(x=>`<div class="pick"><div class="pair">${x.car_no}</div><div>${x.name}</div><div class="right">1着 ${pct(x.p_win)}<br>2連 ${pct(x.p_top2)}<br>3連 ${pct(x.p_top3)}</div></div>`).join('');const prev=data.previous_day||{},prevStatus=prev.status||'',prevFallback=prevStatus==='FIRST_DAY_SKIPPED'?'初日：前日評価なし':prevStatus==='OK'?'前日：負けて強し／展開不利の該当なし':'前日情報なし（PR31単体で計算）';const prevRows=(prev.matched_riders||[]).map(x=>`<div><b>${x.name}</b> 前日${x.finish??'-'}着 ${(x.validated_patterns||[]).map(t=>`<span class="tag">${t}</span>`).join('')}<div class="sub">${x.comment||''}</div></div>`).join('')||`<div class="sub">${prevFallback}</div>`;return `<section class="card"><h2>${data.purchase_status==='BET'?'購入':'見送り'}</h2>${picks}</section><section class="card"><h2>負けて強し／展開不利</h2>${prevRows}</section><section class="card"><h2>全選手率</h2>${riders}</section>`;}
function validateFiles(){const files=[basicPdf.files[0],hsPdf.files[0],oddsPdf.files[0]];if(files.some(file=>!file))return '3種類のPDFをそれぞれ1枚ずつ選んでください。';if(files.some(file=>!file.name.toLowerCase().endsWith('.pdf')))return 'PDFファイルだけ選んでください。';if(files.some(file=>file.size<=0))return '空のPDFが含まれています。選び直してください。';if(files.some(file=>file.size>25*1024*1024))return 'PDFは1枚25MB以下にしてください。';const keys=files.map(file=>`${file.name}|${file.size}|${file.lastModified}`);if(new Set(keys).size!==3)return '同じPDFが重複しています。3種類を選んでください。';return '';}
async function requestCalculation(){let lastError=null;for(let attempt=0;attempt<3;attempt++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),120000);try{const response=await fetch('/analyze',{method:'POST',body:new FormData(form),signal:controller.signal});const raw=await response.text();let data;try{data=JSON.parse(raw);}catch(_){data=null;}if([502,503,504].includes(response.status)){lastError=new Error('サーバー起動待ちです。');if(attempt<2){statusEl.textContent=`サーバー起動待ちです。自動でもう一度試しています… (${attempt+2}/3)`;await sleep(2500*(attempt+1));continue;}}if(!data)throw new Error('サーバー応答を確認できません。自動再試行しても復旧しませんでした。');if(!response.ok)throw new Error(data.error?.message||data.detail||'PDFを確認してもう一度計算してください。');return data;}catch(err){lastError=err;if(attempt<2&&(err?.name==='AbortError'||err instanceof TypeError)){statusEl.textContent=`通信が不安定です。自動でもう一度試しています… (${attempt+2}/3)`;await sleep(2500*(attempt+1));continue;}if(err?.name==='AbortError')throw new Error('計算が時間内に完了しませんでした。もう一度押してください。');throw err;}finally{clearTimeout(timer);}}throw lastError||new Error('計算を完了できませんでした。');}
form.addEventListener('submit',async e=>{e.preventDefault();errorEl.textContent='';result.hidden=true;const validationError=validateFiles();if(validationError){errorEl.textContent=validationError;return;}submit.disabled=true;statusEl.textContent='PR31で計算中…';try{const data=await requestCalculation();result.innerHTML=render(data);result.hidden=false;statusEl.textContent='計算完了';}catch(err){statusEl.textContent='';errorEl.textContent=err.message||String(err);}finally{submit.disabled=false;}});
</script></body></html>"""
