INDEX_HTML = """<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><meta name="theme-color" content="#07643f"><title>章悟式∞競輪OS</title>
<style>
:root{font-family:system-ui,-apple-system,"Noto Sans JP",sans-serif;color:#17212b;background:#f3f5f7}*{box-sizing:border-box}[hidden]{display:none!important}body{margin:0}.wrap{max-width:760px;margin:auto;padding:12px}.card{background:#fff;border-radius:20px;padding:18px;margin:14px 0;box-shadow:0 8px 24px #17212b12}h1{font-size:26px;margin:12px 2px 16px}.lead{line-height:1.6}.notice{padding:13px;border-radius:13px;background:#edf8f2;color:#075f3b;font-weight:750;line-height:1.55}.file-box{display:flex;align-items:center;justify-content:center;width:100%;min-height:82px;margin-top:16px;border:2px solid #087d49;border-radius:16px;background:#f2faf6;cursor:pointer;font-size:19px;font-weight:900}.native{position:absolute;width:1px;height:1px;opacity:0}.selected-list{margin:12px 0 0;padding:0;list-style:none}.selected-item{display:flex;align-items:center;gap:8px;padding:11px 6px;border-bottom:1px solid #e5eaed}.selected-name{min-width:0;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.remove{border:0;border-radius:9px;padding:8px 10px;background:#eef1f3;color:#8a1b1b;font-weight:800}.count{margin:10px 2px;color:#52606a;font-weight:700}.field{margin-top:18px}.field-title{font-weight:900;font-size:17px}.image-box{display:flex;align-items:center;gap:12px;min-height:72px;margin-top:8px;padding:12px;border:2px solid #b8c2cb;border-radius:16px;cursor:pointer}.image-box.selected{border-color:#087d49;background:#f2faf6}.image-button{padding:11px 13px;border:1px solid #75808a;border-radius:9px;background:#f8f9fa;font-weight:800}.image-name{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#6c7780}.settings{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:18px}.settings label{font-weight:850}.settings input{width:100%;height:52px;margin-top:7px;padding:10px 12px;border:1px solid #aeb8c2;border-radius:12px;font-size:18px}.submit{width:100%;min-height:68px;margin-top:22px;border:0;border-radius:16px;background:#087d49;color:white;font-size:19px;font-weight:900}.submit:disabled{opacity:.55}.status{min-height:24px;margin:16px 2px 0;font-weight:800}.error{color:#b11919;white-space:pre-wrap;font-weight:800;line-height:1.5}.result-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.result-card{background:#fff;border-radius:18px;padding:16px}.pick{display:grid;grid-template-columns:70px 1fr 76px;gap:8px;align-items:center;padding:11px 0;border-bottom:1px solid #e6eaed}.pair{font-size:21px;font-weight:900}.prob{font-size:14px;color:#52606a}.ev{text-align:right;font-weight:900}@media(max-width:600px){.result-grid,.settings{grid-template-columns:1fr}.file-box{min-height:88px}}
</style></head><body><main class="wrap"><h1>章悟式∞競輪OS</h1><section class="card"><p class="lead"><b>もうPDFの種類を選び分ける必要なし。</b></p><div class="notice">KEIRIN.JPで保存したPDFをまとめて追加してください。<br>基本情報・着度数/H/S・2車単オッズを自動判定し、直近成績や対戦成績など余計なPDFは無視します。1枚ずつ追加してもOKです。</div>
<form id="form"><label class="file-box" for="pdfs">KEIRIN.JPのPDFを追加</label><input class="native" id="pdfs" name="files" type="file" accept="application/pdf" multiple required><div id="count" class="count">PDF 0枚</div><ul id="selected" class="selected-list"></ul>
<div class="field"><div class="field-title">EX画像 <small>任意</small></div><label class="image-box" id="imageBox" for="ex_image"><span class="image-button">画像を選択</span><span class="image-name" id="imageName">選択されていません</span></label><input class="native" id="ex_image" name="ex_image" type="file" accept="image/png,image/jpeg,image/webp"></div>
<div class="settings"><label>残差λ<input type="number" name="lambda_value" min="0" max="1" step="0.05" value="0.50"></label><label>専用PIN<input type="password" name="pin" autocomplete="current-password"></label></div><button class="submit" id="submit" type="submit">しょーご式5点＋残差3点を計算</button></form><p id="status" class="status"></p><p id="error" class="error"></p></section>
<section id="result" class="result-grid" hidden><div class="result-card"><h2>しょーご式（5点）</h2><div id="shogo"></div></div><div class="result-card"><h2>市場残差（3点）</h2><div id="residual"></div></div></section></main>
<script>
const form=document.querySelector('#form'),pdfInput=document.querySelector('#pdfs'),selected=document.querySelector('#selected'),count=document.querySelector('#count'),statusEl=document.querySelector('#status'),errorEl=document.querySelector('#error'),resultEl=document.querySelector('#result'),submitEl=document.querySelector('#submit'),shogoEl=document.querySelector('#shogo'),residualEl=document.querySelector('#residual');
let files=[];
const key=f=>`${f.name}:${f.size}:${f.lastModified}`;
function sync(){const dt=new DataTransfer();files.forEach(f=>dt.items.add(f));pdfInput.files=dt.files;count.textContent=`PDF ${files.length}枚`;selected.innerHTML=files.map((f,i)=>`<li class="selected-item"><span class="selected-name">${f.name}</span><button class="remove" type="button" data-index="${i}">削除</button></li>`).join('');}
pdfInput.addEventListener('change',()=>{const existing=new Set(files.map(key));for(const f of pdfInput.files){if(!existing.has(key(f))){files.push(f);existing.add(key(f));}}sync();errorEl.textContent='';});
selected.addEventListener('click',e=>{const b=e.target.closest('.remove');if(!b)return;files.splice(Number(b.dataset.index),1);sync();});
const imageInput=document.querySelector('#ex_image'),imageName=document.querySelector('#imageName'),imageBox=document.querySelector('#imageBox');imageInput.addEventListener('change',()=>{const f=imageInput.files&&imageInput.files[0];imageName.textContent=f?f.name:'選択されていません';imageBox.classList.toggle('selected',!!f);});
function clearResult(){resultEl.hidden=true;shogoEl.innerHTML='';residualEl.innerHTML='';}
function renderRows(items){if(!items||!items.length)return '<div>候補なし</div>';return items.map(v=>`<div class="pick"><div class="pair">${v.pair.join('-')}</div><div class="prob">確率 ${(Number(v.probability)*100).toFixed(1)}%<br>オッズ ${Number(v.odds).toFixed(1)}</div><div class="ev">EV<br>${Number(v.conservative_ev).toFixed(2)}</div></div>`).join('');}
form.addEventListener('submit',async e=>{e.preventDefault();errorEl.textContent='';clearResult();if(files.length<3){errorEl.textContent='PDFを3枚以上追加してください。余計なPDFが混ざっても大丈夫です。';return;}submitEl.disabled=true;statusEl.textContent='PDFを自動判定して計算中…';try{const response=await fetch('/analyze-bundle',{method:'POST',body:new FormData(form)});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||data.detail||'計算に失敗しました');shogoEl.innerHTML=renderRows(data.strategies?.shogo?.candidates);residualEl.innerHTML=renderRows(data.strategies?.residual?.candidates);resultEl.hidden=false;statusEl.textContent='計算完了';resultEl.scrollIntoView({behavior:'smooth',block:'start'});}catch(err){clearResult();statusEl.textContent='';errorEl.textContent=err.message;}finally{submitEl.disabled=false;}});
</script></body></html>"""
